name: 'Pull request'

on:
  pull_request:
    branches:
      - 'main'

jobs:
  pull_request:
    name: 'Pull request'
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Load code'
        uses: 'actions/checkout@v3'
      - name: 'Setup Java'
        uses: 'actions/setup-java@v2'
        with:
          distribution: 'zulu'
          java-version: 19
      - name: 'Prebuild'
        run: 'chmod +x ./gradlew'
      - name: 'Run tests'
        run: './gradlew test'
      - name: 'Build'
        run: './gradlew build'
