name: 'Release'

on:
  push:
    branches:
      - 'main'

env:
  KEYSTORE_HOST: '${{ secrets.KEYSTORE_HOST }}'
  KEYSTORE_ACCESS_TOKEN: '${{ secrets.KEYSTORE_ACCESS_TOKEN }}'

jobs:
  Release:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'write'

    steps:
      - name: 'Load code'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 2
      - name: 'Setup Java'
        uses: 'actions/setup-java@v2'
        with:
          distribution: 'zulu'
          java-version: 19
      - name: 'Prebuild'
        run: 'chmod +x ./gradlew'
      - name: 'Run tests'
        run: './gradlew test'
      - name: 'Build'
        run: './gradlew build'
      - name: 'Publish'
        run: 'chmod +x scripts/publish.sh && scripts/publish.sh'
